local _, ns = ...

ns.constants = ns.constants or {}
local C = ns.constants

C.VERSION = "1.4.0"
C.SLASH_COMMAND = "/aixport"
C.ADDON_TITLE = "AIExport"

C.FOREVER_INTERFACE = 16001
C.FOREVER_VERSION = "1.60.1"

C.SECTIONS = {
    LOCATION = "location",
    CHARACTER_STATS = "character_stats",
    CURRENCIES = "currencies",
    COLLECTIONS = "collections",
    BAGS = "bags",
    BANK = "bank",
    EQUIPMENT = "equipment",
    LOCKOUTS = "lockouts",
    PROGRESS = "progress",
    ACHIEVEMENTS = "achievements",
    COMPLETED_ACHIEVEMENTS = "completed_achievements",
    COLLECTED_APPEARANCES = "collected_appearances",
    APPEARANCES = "appearances",
    REPUTATIONS = "reputations",
    QUESTS = "quests",
    COMPLETED_QUESTS = "completed_quests",
    SKILLS = "skills",
    PROFESSION_DETAILS = "profession_details",
    TALENTS = "talents",
    SPELLBOOK = "spellbook",
    BIOGRAPHY = "biography",
    KILLS = "kills",
    COMPANIONS = "companions",
    ADDONS = "addons",
}

C.SECTION_ORDER = {
    C.SECTIONS.LOCATION,
    C.SECTIONS.CHARACTER_STATS,
    C.SECTIONS.CURRENCIES,
    C.SECTIONS.COLLECTIONS,
    C.SECTIONS.BAGS,
    C.SECTIONS.BANK,
    C.SECTIONS.EQUIPMENT,
    C.SECTIONS.LOCKOUTS,
    C.SECTIONS.PROGRESS,
    C.SECTIONS.KILLS,
    C.SECTIONS.ACHIEVEMENTS,
    C.SECTIONS.COMPLETED_ACHIEVEMENTS,
    C.SECTIONS.COLLECTED_APPEARANCES,
    C.SECTIONS.APPEARANCES,
    C.SECTIONS.REPUTATIONS,
    C.SECTIONS.QUESTS,
    C.SECTIONS.COMPLETED_QUESTS,
    C.SECTIONS.SKILLS,
    C.SECTIONS.PROFESSION_DETAILS,
    C.SECTIONS.TALENTS,
    C.SECTIONS.SPELLBOOK,
    C.SECTIONS.BIOGRAPHY,
    C.SECTIONS.COMPANIONS,
    C.SECTIONS.ADDONS,
}

C.SECTION_LABELS = {
    [C.SECTIONS.LOCATION] = "Location",
    [C.SECTIONS.CHARACTER_STATS] = "Character Stats",
    [C.SECTIONS.CURRENCIES] = "Currencies",
    [C.SECTIONS.COLLECTIONS] = "Collections",
    [C.SECTIONS.BAGS] = "Bags",
    [C.SECTIONS.BANK] = "Bank",
    [C.SECTIONS.EQUIPMENT] = "Equipment",
    [C.SECTIONS.LOCKOUTS] = "Lockouts",
    [C.SECTIONS.PROGRESS] = "Progress",
    [C.SECTIONS.ACHIEVEMENTS] = "Achievements",
    [C.SECTIONS.COMPLETED_ACHIEVEMENTS] = "Achievement (completed)",
    [C.SECTIONS.COLLECTED_APPEARANCES] = "Appearance (collected)",
    [C.SECTIONS.APPEARANCES] = "Appearances",
    [C.SECTIONS.REPUTATIONS] = "Reputations",
    [C.SECTIONS.QUESTS] = "Quests",
    [C.SECTIONS.COMPLETED_QUESTS] = "Quest (completed)",
    [C.SECTIONS.SKILLS] = "Skills",
    [C.SECTIONS.PROFESSION_DETAILS] = "Profession Details",
    [C.SECTIONS.TALENTS] = "Talents",
    [C.SECTIONS.SPELLBOOK] = "Spellbook",
    [C.SECTIONS.BIOGRAPHY] = "Biography",
    [C.SECTIONS.KILLS] = "Kills",
    [C.SECTIONS.COMPANIONS] = "Companions",
    [C.SECTIONS.ADDONS] = "AddOns",
}

C.SECTION_GROUPS = {
    {
        title = "Character",
        sections = {
            C.SECTIONS.LOCATION,
            C.SECTIONS.CHARACTER_STATS,
            C.SECTIONS.EQUIPMENT,
            C.SECTIONS.REPUTATIONS,
            C.SECTIONS.CURRENCIES,
        },
    },
    {
        title = "Inventory",
        sections = {
            C.SECTIONS.BAGS,
            C.SECTIONS.BANK,
            C.SECTIONS.COLLECTIONS,
            C.SECTIONS.APPEARANCES,
            C.SECTIONS.COLLECTED_APPEARANCES,
        },
    },
    {
        title = "Progress",
        sections = {
            C.SECTIONS.PROGRESS,
            C.SECTIONS.QUESTS,
            C.SECTIONS.COMPLETED_QUESTS,
            C.SECTIONS.ACHIEVEMENTS,
            C.SECTIONS.COMPLETED_ACHIEVEMENTS,
            C.SECTIONS.LOCKOUTS,
            C.SECTIONS.KILLS,
        },
    },
    {
        title = "Abilities",
        sections = {
            C.SECTIONS.SKILLS,
            C.SECTIONS.PROFESSION_DETAILS,
            C.SECTIONS.TALENTS,
            C.SECTIONS.SPELLBOOK,
        },
    },
    {
        title = "Story",
        sections = {
            C.SECTIONS.BIOGRAPHY,
        },
    },
    {
        title = "System",
        sections = {
            C.SECTIONS.ADDONS,
            C.SECTIONS.COMPANIONS,
        },
    },
}

C.DEFAULT_SELECTIONS = {
    [C.SECTIONS.LOCATION] = true,
    [C.SECTIONS.CHARACTER_STATS] = true,
    [C.SECTIONS.CURRENCIES] = true,
    [C.SECTIONS.COLLECTIONS] = true,
    [C.SECTIONS.BAGS] = true,
    [C.SECTIONS.BANK] = true,
    [C.SECTIONS.EQUIPMENT] = true,
    [C.SECTIONS.LOCKOUTS] = true,
    [C.SECTIONS.PROGRESS] = true,
    [C.SECTIONS.ACHIEVEMENTS] = true,
    [C.SECTIONS.COMPLETED_ACHIEVEMENTS] = false,
    [C.SECTIONS.COLLECTED_APPEARANCES] = false,
    [C.SECTIONS.APPEARANCES] = true,
    [C.SECTIONS.REPUTATIONS] = true,
    [C.SECTIONS.QUESTS] = true,
    [C.SECTIONS.COMPLETED_QUESTS] = true,
    [C.SECTIONS.SKILLS] = true,
    [C.SECTIONS.PROFESSION_DETAILS] = true,
    [C.SECTIONS.TALENTS] = true,
    [C.SECTIONS.SPELLBOOK] = true,
    [C.SECTIONS.BIOGRAPHY] = true,
    [C.SECTIONS.KILLS] = true,
    [C.SECTIONS.COMPANIONS] = true,
    [C.SECTIONS.ADDONS] = true,
}

C.KILLS_EXPORT_TOP = 25
C.KILLS_EXPORT_DROPS = 60
C.KILLS_PANEL_DEFAULT_OPACITY = 96

C.TEXT = {
    BANK_UNAVAILABLE = "[Bank data unavailable.]",
    BANK_UNAVAILABLE_NO_CACHE = "[Bank data unavailable - open your personal bank at least once to build cache.]",
    BANK_CACHED_PREFIX = "[Using cached bank data",
    PROFESSION_DETAILS_UNAVAILABLE_NO_CACHE = "[Profession details unavailable - open each profession window at least once to build cache.]",
    PROFESSION_DETAILS_CACHED_PREFIX = "[Using cached profession details",
    NOTHING_SELECTED = "[No export sections selected.]",
    NOTHING_TO_EXPORT = "[No data available to export.]",
    EXPORT_WINDOW_TITLE = "AIExport - Export Text",
    GUIDE_WINDOW_TITLE = "AIExport - How to use",
    MAIN_WINDOW_TITLE = "AIExport",
    BUTTON_EXPORT = "Create Export",
    BUTTON_SELECT_ALL = "Select All",
    BUTTON_CLEAR_ALL = "Clear All",
    BUTTON_RELOAD_UI = "Reload UI",
    BUTTON_OLDER = "Older",
    BUTTON_NEWER = "Newer",
    BUTTON_COPY_GUIDE = "Copy guide",
    BIOGRAPHY_EMPTY = "No events yet. AIExport records level-ups, deaths, new zones, quest turn-ins, achievements, profession skill-ups, and screenshots from now on.",
    LABEL_SUBTITLE = "Character reports for AI chats",
    LABEL_EXPORT_HINT = "Ctrl+C to copy, then paste into your AI chat",
    LABEL_MAIN_DESCRIPTION = "Choose what goes into the report, then press Create Export and paste the text into an AI chat.",
    LABEL_BANK_HINT = "Bank and profession details use the last copy saved while those windows were open.",
    LABEL_COMPANIONS_DESCRIPTION = "AIExport works on its own. When one of these addons is loaded, AIExport can add its data to the Companions section of the export. Switch any of them off here.",
    LABEL_COMPANIONS_SECTION_OFF = "The Companions section is off in the Export tab, so none of these are exported.",
    LABEL_BIOGRAPHY_DESCRIPTION = "Everything AIExport has seen happen to this character. The export always includes the full timeline.",
    LABEL_OPTIONS = "Options",
    TAB_EXPORT = "Export",
    TAB_COMPANIONS = "Companions",
    TAB_BIOGRAPHY = "Biography",
    TAB_HELP = "Help",
    STATUS_LOADED = "Loaded",
    STATUS_INSTALLED = "Installed, not loaded",
    STATUS_MISSING = "Not installed",
    COMPANIONS_NONE = "No companion addons are loaded and switched on.",
    LABEL_SHOW_MINIMAP_ICON = "Show minimap icon",
    LABEL_VERBOSE_ITEM_TYPES = "Item stats in bags and bank",
    LABEL_DETAILED_EXPORT = "Detailed export (IDs and full item details, much larger)",
    LABEL_TOKEN_ESTIMATE = "About %s tokens (%s characters)",
    LABEL_TOKEN_LARGEST = "Largest: %s",
    LABEL_TOKEN_SMALL = "Fits in any AI chat.",
    LABEL_TOKEN_MEDIUM = "Fits in most AI chats.",
    LABEL_TOKEN_LARGE = "Large. Untick the biggest sections if your AI chat cuts it off.",
    LABEL_LAST_EXPORT = "Last export: about %s tokens",
    LABEL_MISSING = "Missing: %s",
    READINESS_BANK_MISSING = "Bank not saved yet. Open your bank once.",
    READINESS_BANK_STALE = "Bank saved %s ago. Open it to refresh.",
    READINESS_PROFESSION_MISSING = "%s not saved yet. Open its window once.",
    READINESS_PROFESSION_STALE = "%s saved %s ago. Open its window to refresh.",
    READINESS_USING_FALLBACK = "Using %s's copy for now.",
    PROFESSION_MASTER_FALLBACK_NOTE = "(From Profession Master; open the profession window to refresh.)",
    SYNDICATOR_BANK_FALLBACK_NOTE = "(From Syndicator; open your bank to refresh.)",
    TAB_KILLS = "Kills",
    KILLS_TOOLTIP = "Killed %d time%s",
    KILLS_EMPTY = "No kills yet. AIExport counts every creature you or your pet finish off, outside dungeons and raids.",
    KILLS_NO_MATCH = "No creature matches that search.",
    KILLS_HEADER = "Lifetime %s kills of %s creatures   Session %s (%s per hour)   Gold looted %s",
    KILLS_IMPORTED = "Includes %s kills copied from KillDex.",
    KILLS_SEARCH = "Search",
    KILLS_SORT_KILLS = "Most kills",
    KILLS_SORT_NAME = "Name",
    KILLS_SORT_RECENT = "Recent",
    KILLS_DETAIL_EMPTY = "Click a creature to see its drops.",
    KILLS_NO_DROPS = "No drops recorded.",
    KILLS_SHOW_PANEL = "Show live kill panel",
    KILLS_SHOW_TOOLTIP = "Kill count on creature tooltips",
    KILLS_PANEL_TITLE = "Kills",
    KILLS_PANEL_SESSION = "Session: %s kills, %s per hour",
    KILLS_PANEL_EMPTY = "Nothing killed this session yet.",
    KILLS_PANEL_LOCK = "Lock",
    KILLS_PANEL_UNLOCK = "Unlock",
    KILLS_PANEL_OPACITY = "Panel background",
    KILLS_PANEL_OPACITY_VALUE = "%d%%",
    KILLDEX_BUILT_IN = "Built into AIExport",
    MINIMAP_LEFT_CLICK = "Left-click to open the export window.",
    MINIMAP_RIGHT_CLICK = "Right-click to show or hide the kill panel.",
}

C.CHARACTERS_PER_TOKEN = 4
C.TOKENS_SMALL = 8000
C.TOKENS_MEDIUM = 32000

C.EQUIPMENT_SLOTS = {
    { slotId = INVSLOT_HEAD, slotToken = "HeadSlot", label = "Head" },
    { slotId = INVSLOT_NECK, slotToken = "NeckSlot", label = "Neck" },
    { slotId = INVSLOT_SHOULDER, slotToken = "ShoulderSlot", label = "Shoulder" },
    { slotId = INVSLOT_BACK, slotToken = "BackSlot", label = "Back" },
    { slotId = INVSLOT_CHEST, slotToken = "ChestSlot", label = "Chest" },
    { slotId = INVSLOT_BODY or INVSLOT_SHIRT, slotToken = "ShirtSlot", label = "Shirt" },
    { slotId = INVSLOT_TABARD, slotToken = "TabardSlot", label = "Tabard" },
    { slotId = INVSLOT_WRIST, slotToken = "WristSlot", label = "Wrist" },
    { slotId = INVSLOT_HAND, slotToken = "HandsSlot", label = "Hands" },
    { slotId = INVSLOT_WAIST, slotToken = "WaistSlot", label = "Waist" },
    { slotId = INVSLOT_LEGS, slotToken = "LegsSlot", label = "Legs" },
    { slotId = INVSLOT_FEET, slotToken = "FeetSlot", label = "Feet" },
    { slotId = INVSLOT_FINGER1, slotToken = "Finger0Slot", label = "Finger 1" },
    { slotId = INVSLOT_FINGER2, slotToken = "Finger1Slot", label = "Finger 2" },
    { slotId = INVSLOT_TRINKET1, slotToken = "Trinket0Slot", label = "Trinket 1" },
    { slotId = INVSLOT_TRINKET2, slotToken = "Trinket1Slot", label = "Trinket 2" },
    { slotId = INVSLOT_MAINHAND, slotToken = "MainHandSlot", label = "Main Hand" },
    { slotId = INVSLOT_OFFHAND, slotToken = "SecondaryHandSlot", label = "Off Hand" },
}

C.SKILL_CATEGORY_LABELS = {
    PROFESSIONS = "Professions",
    SECONDARY = "Secondary Skills",
    WEAPON = "Weapon Skills",
    OTHER = "Other Skills",
}