local _, ns = ...

ns.constants = ns.constants or {}
local C = ns.constants

C.VERSION = "2.2.10"
C.SLASH_COMMAND = "/dossier"
C.SLASH_ALIAS = "/aixport"
C.ADDON_TITLE = "Dossier"
C.OLD_ADDON_NAME = "AIExport"

C.FOREVER_INTERFACE = 16001
C.FOREVER_VERSION = "1.60.1"

C.SECTIONS = {
    LOCATION = "location",
    CHARACTER_STATS = "character_stats",
    CURRENCIES = "currencies",
    COLLECTIONS = "collections",
    BAGS = "bags",
    BANK = "bank",
    EQUIPMENT = "equipment",
    LOCKOUTS = "lockouts",
    PROGRESS = "progress",
    ACHIEVEMENTS = "achievements",
    COMPLETED_ACHIEVEMENTS = "completed_achievements",
    COLLECTED_APPEARANCES = "collected_appearances",
    APPEARANCES = "appearances",
    REPUTATIONS = "reputations",
    QUESTS = "quests",
    COMPLETED_QUESTS = "completed_quests",
    SKILLS = "skills",
    PROFESSION_DETAILS = "profession_details",
    TALENTS = "talents",
    SPELLBOOK = "spellbook",
    BIOGRAPHY = "biography",
    KILLS = "kills",
    SESSIONS = "sessions",
    STATISTICS = "statistics",
    COMPANIONS = "companions",
    ADDONS = "addons",
    SHOPPING = "shopping",
}

C.SECTION_ORDER = {
    C.SECTIONS.LOCATION,
    C.SECTIONS.CHARACTER_STATS,
    C.SECTIONS.CURRENCIES,
    C.SECTIONS.COLLECTIONS,
    C.SECTIONS.BAGS,
    C.SECTIONS.BANK,
    C.SECTIONS.SHOPPING,
    C.SECTIONS.EQUIPMENT,
    C.SECTIONS.LOCKOUTS,
    C.SECTIONS.PROGRESS,
    C.SECTIONS.KILLS,
    C.SECTIONS.SESSIONS,
    C.SECTIONS.STATISTICS,
    C.SECTIONS.ACHIEVEMENTS,
    C.SECTIONS.COMPLETED_ACHIEVEMENTS,
    C.SECTIONS.COLLECTED_APPEARANCES,
    C.SECTIONS.APPEARANCES,
    C.SECTIONS.REPUTATIONS,
    C.SECTIONS.QUESTS,
    C.SECTIONS.COMPLETED_QUESTS,
    C.SECTIONS.SKILLS,
    C.SECTIONS.PROFESSION_DETAILS,
    C.SECTIONS.TALENTS,
    C.SECTIONS.SPELLBOOK,
    C.SECTIONS.BIOGRAPHY,
    C.SECTIONS.ADDONS,
}

C.SECTION_LABELS = {
    [C.SECTIONS.LOCATION] = "Location",
    [C.SECTIONS.CHARACTER_STATS] = "Character Stats",
    [C.SECTIONS.CURRENCIES] = "Currencies",
    [C.SECTIONS.COLLECTIONS] = "Collections",
    [C.SECTIONS.BAGS] = "Bags",
    [C.SECTIONS.BANK] = "Bank",
    [C.SECTIONS.EQUIPMENT] = "Equipment",
    [C.SECTIONS.LOCKOUTS] = "Lockouts",
    [C.SECTIONS.PROGRESS] = "Progress",
    [C.SECTIONS.ACHIEVEMENTS] = "Achievements",
    [C.SECTIONS.COMPLETED_ACHIEVEMENTS] = "Achievement (completed)",
    [C.SECTIONS.COLLECTED_APPEARANCES] = "Appearance (collected)",
    [C.SECTIONS.APPEARANCES] = "Appearances",
    [C.SECTIONS.REPUTATIONS] = "Reputations",
    [C.SECTIONS.QUESTS] = "Quests",
    [C.SECTIONS.COMPLETED_QUESTS] = "Quest (completed)",
    [C.SECTIONS.SKILLS] = "Skills",
    [C.SECTIONS.PROFESSION_DETAILS] = "Profession Details",
    [C.SECTIONS.TALENTS] = "Talents",
    [C.SECTIONS.SPELLBOOK] = "Spellbook",
    [C.SECTIONS.BIOGRAPHY] = "Biography",
    [C.SECTIONS.KILLS] = "Kills",
    [C.SECTIONS.SESSIONS] = "Sessions",
    [C.SECTIONS.STATISTICS] = "Statistics",
    [C.SECTIONS.COMPANIONS] = "Companions",
    [C.SECTIONS.ADDONS] = "AddOns",
    [C.SECTIONS.SHOPPING] = "Shopping list",
}

C.SECTION_GROUPS = {
    {
        title = "Character",
        sections = {
            C.SECTIONS.LOCATION,
            C.SECTIONS.CHARACTER_STATS,
            C.SECTIONS.EQUIPMENT,
            C.SECTIONS.REPUTATIONS,
            C.SECTIONS.CURRENCIES,
        },
    },
    {
        title = "Inventory",
        sections = {
            C.SECTIONS.BAGS,
            C.SECTIONS.BANK,
            C.SECTIONS.SHOPPING,
            C.SECTIONS.COLLECTIONS,
            C.SECTIONS.APPEARANCES,
            C.SECTIONS.COLLECTED_APPEARANCES,
        },
    },
    {
        title = "Progress",
        sections = {
            C.SECTIONS.PROGRESS,
            C.SECTIONS.QUESTS,
            C.SECTIONS.COMPLETED_QUESTS,
            C.SECTIONS.ACHIEVEMENTS,
            C.SECTIONS.COMPLETED_ACHIEVEMENTS,
            C.SECTIONS.LOCKOUTS,
            C.SECTIONS.KILLS,
            C.SECTIONS.STATISTICS,
        },
    },
    {
        title = "Abilities",
        sections = {
            C.SECTIONS.SKILLS,
            C.SECTIONS.PROFESSION_DETAILS,
            C.SECTIONS.TALENTS,
            C.SECTIONS.SPELLBOOK,
        },
    },
    {
        title = "Story",
        sections = {
            C.SECTIONS.BIOGRAPHY,
            C.SECTIONS.SESSIONS,
        },
    },
    {
        title = "System",
        sections = {
            C.SECTIONS.ADDONS,
            C.SECTIONS.COMPANIONS,
        },
    },
}

C.DEFAULT_SELECTIONS = {
    [C.SECTIONS.LOCATION] = true,
    [C.SECTIONS.CHARACTER_STATS] = true,
    [C.SECTIONS.CURRENCIES] = true,
    [C.SECTIONS.COLLECTIONS] = true,
    [C.SECTIONS.BAGS] = true,
    [C.SECTIONS.BANK] = true,
    [C.SECTIONS.SHOPPING] = true,
    [C.SECTIONS.EQUIPMENT] = true,
    [C.SECTIONS.LOCKOUTS] = true,
    [C.SECTIONS.PROGRESS] = true,
    [C.SECTIONS.ACHIEVEMENTS] = true,
    [C.SECTIONS.COMPLETED_ACHIEVEMENTS] = false,
    [C.SECTIONS.COLLECTED_APPEARANCES] = false,
    [C.SECTIONS.APPEARANCES] = true,
    [C.SECTIONS.REPUTATIONS] = true,
    [C.SECTIONS.QUESTS] = true,
    [C.SECTIONS.COMPLETED_QUESTS] = true,
    [C.SECTIONS.SKILLS] = true,
    [C.SECTIONS.PROFESSION_DETAILS] = true,
    [C.SECTIONS.TALENTS] = true,
    [C.SECTIONS.SPELLBOOK] = true,
    [C.SECTIONS.BIOGRAPHY] = true,
    [C.SECTIONS.KILLS] = true,
    [C.SECTIONS.SESSIONS] = true,
    [C.SECTIONS.STATISTICS] = true,
    [C.SECTIONS.COMPANIONS] = true,
    [C.SECTIONS.ADDONS] = true,
}

C.KILLS_EXPORT_TOP = 25
C.KILLS_EXPORT_DROPS = 60
C.KILLS_PANEL_DEFAULT_OPACITY = 96

C.SESSION_CATEGORY_LABELS = {
    herb = "Herb",
    ore = "Ore and stone",
    leather = "Leather",
    cloth = "Cloth",
    cooking = "Cooking and fish",
    elemental = "Elemental",
    enchanting = "Enchanting",
    jewelcrafting = "Jewelcrafting",
    reagent = "Reagent",
    holiday = "Holiday",
    consumable = "Consumable",
    quest = "Quest item",
}

C.TASK_PANEL_LINES = { "tasks", "shopping", "rares" }

C.TASK_PANEL_LINE_LABELS = {
    tasks = "Tasks here",
    shopping = "Shopping short",
    rares = "Rares here",
}

C.SESSION_PANEL_LINES = { "kills", "gathered", "gold", "xp", "recent" }

C.SESSION_PANEL_LINE_LABELS = {
    kills = "Kills",
    gathered = "Gathered",
    gold = "Gold",
    xp = "XP and time to level",
    recent = "Recent creatures",
}

C.SESSION_EXPORT_ITEMS = 10
C.SESSION_EXPORT_HISTORY = 10

C.SHOTS_INTERVAL_MIN = 5
C.SHOTS_INTERVAL_MAX = 60
C.SHOTS_INTERVAL_DEFAULT = 5

C.SHOTS_TRIGGER_LABELS = {
    levelUp = "Level up",
    death = "Death",
    achievement = "Achievement earned",
    boss = "Dungeon or raid boss killed",
    pvp = "Battleground or arena ends",
    duel = "Duel finished",
    collection = "New mount, pet, toy, or recipe",
    login = "Login",
    interval = "Every few minutes",
}

C.SHOTS_TRIGGER_REASONS = {
    levelUp = "Level up",
    death = "Died",
    achievement = "Achievement earned",
    boss = "Boss defeated",
    pvp = "PvP match ended",
    duel = "Duel finished",
    collection = "New collectible",
    login = "Logged in",
    interval = "Timed screenshot",
}

C.SHOTS_COLLECTION_LABELS = {
    NEW_MOUNT_ADDED = "New mount",
    NEW_PET_ADDED = "New pet",
    NEW_TOY_ADDED = "New toy",
    NEW_RECIPE_LEARNED = "New recipe",
}

C.SHOTS_OPTION_LABELS = {
    hideUI = "Hide the interface",
    stamp = "Add a name and date stamp",
    sound = "Camera sound",
    chat = "Chat message for each screenshot",
}

C.TEXT = {
    BANK_UNAVAILABLE = "[Bank data unavailable.]",
    BANK_UNAVAILABLE_NO_CACHE = "[Bank data unavailable - open your personal bank at least once to build cache.]",
    BANK_CACHED_PREFIX = "[Using cached bank data",
    PROFESSION_DETAILS_UNAVAILABLE_NO_CACHE = "[Profession details unavailable - open each profession window at least once to build cache.]",
    PROFESSION_DETAILS_CACHED_PREFIX = "[Using cached profession details",
    NOTHING_SELECTED = "[No export sections selected.]",
    NOTHING_TO_EXPORT = "[No data available to export.]",
    EXPORT_WINDOW_TITLE = "Dossier - Export Text",
    GUIDE_WINDOW_TITLE = "Dossier - How to use",
    MAIN_WINDOW_TITLE = "Dossier",
    BUTTON_EXPORT = "Create Export",
    BUTTON_SELECT_ALL = "Select All",
    BUTTON_CLEAR_ALL = "Clear All",
    BUTTON_RELOAD_UI = "Reload UI",
    BUTTON_OLDER = "Older",
    BUTTON_NEWER = "Newer",
    BUTTON_COPY_GUIDE = "Copy guide",
    BIOGRAPHY_EMPTY = "No events yet. Dossier records level-ups, deaths, new zones, quest turn-ins, achievements, profession skill-ups, books you open, and screenshots from now on.",
    LABEL_SUBTITLE = "Character reports for AI chats",
    LABEL_EXPORT_HINT = "Ctrl+C to copy, then paste into your AI chat",
    LABEL_MAIN_DESCRIPTION = "Choose what goes into the report, then press Create Export and paste the text into an AI chat.",
    LABEL_BANK_HINT = "Bank and profession details use the last copy saved while those windows were open.",
    LABEL_COMPANIONS_DESCRIPTION = "Dossier works on its own. When one of these addons is loaded, Dossier can add its data to the Companions section of the export. Switch any of them off here.",
    LABEL_COMPANIONS_SECTION_OFF = "The Companions section is off in the Export tab, so none of these are exported.",
    LABEL_BIOGRAPHY_DESCRIPTION = "Everything Dossier has seen happen to this character. The export always includes the full timeline.",
    TAB_EXPORT = "Export",
    TAB_COMPANIONS = "Companions",
    TAB_BIOGRAPHY = "Biography",
    TAB_HELP = "Help",
    STATUS_LOADED = "Loaded",
    STATUS_INSTALLED = "Installed, not loaded",
    STATUS_MISSING = "Not installed",
    COMPANIONS_NONE = "No companion addons are loaded and switched on.",
    LABEL_SHOW_MINIMAP_ICON = "Show minimap icon",
    LABEL_VERBOSE_ITEM_TYPES = "Item stats in bags and bank",
    LABEL_DETAILED_EXPORT = "Detailed export (IDs and full item details, much larger)",
    LABEL_TOKEN_ESTIMATE = "About %s tokens (%s characters)",
    LABEL_TOKEN_LARGEST = "Largest: %s",
    LABEL_TOKEN_SMALL = "Fits in any AI chat.",
    LABEL_TOKEN_MEDIUM = "Fits in most AI chats.",
    LABEL_TOKEN_LARGE = "Large. Untick the biggest sections if your AI chat cuts it off.",
    LABEL_LAST_EXPORT = "Last export: about %s tokens",
    LABEL_MISSING = "Missing: %s",
    READINESS_BANK_MISSING = "Bank not saved yet. Open your bank once.",
    READINESS_BANK_STALE = "Bank saved %s ago. Open it to refresh.",
    READINESS_PROFESSION_MISSING = "%s not saved yet. Open its window once.",
    READINESS_PROFESSION_STALE = "%s saved %s ago. Open its window to refresh.",
    READINESS_USING_FALLBACK = "Using a saved copy for now.",
    PROFESSION_MASTER_FALLBACK_NOTE = "(Saved copy; open the profession window to refresh.)",
    SYNDICATOR_BANK_FALLBACK_NOTE = "(Saved copy; open your bank to refresh.)",
    TAB_KILLS = "Kills",
    KILLS_TOOLTIP = "Killed %d time%s",
    KILLS_EMPTY = "No kills yet. Dossier counts every creature you or your pet finish off, outside dungeons and raids.",
    KILLS_NO_MATCH = "No creature matches that search.",
    KILLS_HEADER = "Lifetime %s kills of %s creatures   Session %s (%s per hour)   Gold looted %s",
    KILLS_IMPORTED = "Includes %s kills copied from KillDex.",
    KILLS_SEARCH = "Search",
    KILLS_SORT_KILLS = "Most kills",
    KILLS_SORT_NAME = "Name",
    KILLS_SORT_RECENT = "Recent",
    KILLS_DETAIL_EMPTY = "Click a creature to see its drops.",
    KILLS_NO_DROPS = "No drops recorded.",
    KILLS_SHOW_PANEL = "Show the session panel",
    KILLS_PANEL_MOVED = "Session panel options are on the Session tab.",
    KILLS_SHOW_TOOLTIP = "Kill count on creature tooltips",
    SESSION_PANEL_TITLE = "Session",
    SESSION_PAUSED = "Paused",
    SESSION_LINE_KILLS = "Kills %s (%s/hr)",
    SESSION_LINE_GATHERED = "Gathered %s (%s/hr)",
    SESSION_LINE_GOLD = "Gold %s (%s/hr)",
    SESSION_LINE_XP = "XP %s (%s/hr)",
    SESSION_LINE_LEVEL = ", level in %s",
    SESSION_TOOLTIP_TITLE = "Gathered this session",
    SESSION_TOOLTIP_EMPTY = "Nothing gathered yet.",
    SESSION_TOOLTIP_ITEM = "%s (%s/hr)",
    SESSION_TOOLTIP_MORE = "and %d more: see the Session tab",
    SESSION_TOOLTIP_HELP = "Click the title to pause or resume the timer. Right-click it to reset the session.",
    TAB_SESSION = "Session",
    TAB_SESSIONS = "Sessions",
    TAB_RARES = "Rares",
    TAB_LEDGER = "Ledger",
    TAB_CURRENCIES = "Currencies",
    TAB_REPUTATION = "Reputation",
    TAB_MAIL = "Mail",
    TAB_PROFESSIONS = "Professions",
    TAB_LOCKOUTS = "Lockouts",
    TAB_TASKS = "Tasks",
    TAB_QUESTS = "Quests",
    SESSION_PAUSE = "Pause",
    SESSION_RESUME = "Start",
    SESSION_RESET = "Reset",
    SESSION_THIS_SESSION = "This session",
    SESSION_PANEL_CARD = "Session panel",
    TASK_PANEL_CARD = "Task panel",
    TASK_SHOW_PANEL = "Show the task panel",
    TASK_OPEN_ZONE = "Open when the zone changes",
    TASK_PANEL_TITLE = "Tasks",
    TASK_PANEL_EMPTY = "Nothing waiting in this zone.",
    SESSION_CATEGORIES = "Count as gathered",
    SESSION_TIME_TO_LEVEL = "Next level in %s",
    SESSION_LEVELS = "Levels gained: %d",
    SESSION_HISTORY_TITLE = "Previous sessions",
    SESSION_HISTORY_EMPTY = "No finished sessions yet. Press Reset to end this one and save it here.",
    SESSION_HISTORY_NOTHING = "nothing recorded",
    SESSION_RESET_CONFIRM = "Reset this session? It is saved to your session history first.",
    KILLS_PANEL_TITLE = "Kills",
    KILLS_PANEL_SESSION = "Session: %s kills, %s per hour",
    KILLS_PANEL_EMPTY = "Nothing killed this session yet.",
    KILLS_PANEL_LOCK = "Lock",
    KILLS_PANEL_UNLOCK = "Unlock",
    KILLS_PANEL_OPACITY = "Panel background",
    KILLS_PANEL_OPACITY_VALUE = "%d%%",
    KILLDEX_BUILT_IN = "Built into Dossier",
    TAB_SCREENSHOTS = "Screenshotter",
    SHOTS_DESCRIPTION = "Takes a screenshot at big moments, like Memento. Screenshots go to the game's Screenshots folder, and each one is noted in the Biography with the reason.",
    SHOTS_ENABLED = "Take screenshots automatically",
    SHOTS_STATUS_ON = "On. Screenshots are taken for the moments ticked below.",
    SHOTS_STATUS_OFF = "Off. No screenshots are taken automatically.",
    SHOTS_STATUS_PAUSED = "Paused while Memento is loaded. Disable Memento to let Dossier take screenshots.",
    SHOTS_TEST = "Take test screenshot",
    SHOTS_TRIGGERS_TITLE = "Take a screenshot when",
    SHOTS_OPTIONS_TITLE = "Options",
    SHOTS_INTERVAL = "Every %d minutes",
    SHOTS_CHAT = "%sDossier|r screenshot: %s",
    SHOTS_REASON_MANUAL = "Test screenshot",
    SHOTS_REASON_LEVEL = "Reached level %d",
    SHOTS_REASON_ACHIEVEMENT = "Earned %s",
    SHOTS_REASON_BOSS = "Defeated %s",
    SHOTS_REASON_INTERVAL = "Timed screenshot (every %d minutes)",
    OLD_ADDON_LOADED = "|cffff8040Dossier:|r AIExport is still loaded. Dossier is its new name, so untick AIExport in the AddOns list and restart the game.",
    SESSIONS_EMPTY = "No sessions recorded yet.",
    SESSIONS_IDLE = "This session: nothing yet.",
    STATISTICS_UNAVAILABLE = "Statistics are not available on this client.",
    STATISTICS_EMPTY = "No statistics recorded yet.",
    MINIMAP_LEFT_CLICK = "Left-click to open the export window.",
    MINIMAP_RIGHT_CLICK = "Right-click to show or hide the session panel.",
    TAB_OPTIONS = "Options",
    LABEL_GENERAL = "General (this character)",
    LABEL_FEATURES = "Features (every character)",
    BUTTON_OPEN_DOSSIER = "Open Dossier",
    SETTINGS_PAGE_DESCRIPTION = "Copy your character into an AI chat. These are the same options as the Options tab in the Dossier window (/dossier options).",
    FEATURES_DESCRIPTION = "Turning a feature off stops it recording and hides its tab and export section. What it already saved stays and comes back when you turn it on. These switches apply to every character on this account.",
    FEATURES_ALWAYS_ON = "Always on: the Export tab and its other sections, the saved bank and profession copies, Help, and these options.",
    FEATURE_OFF = "|cffff8040Dossier:|r %s is turned off. Turn it on in the Options tab (/dossier options).",
    FEATURE_TURNED_ON = "|cff5cc8a8Dossier:|r %s is on.",
    FEATURE_TURNED_OFF = "|cff5cc8a8Dossier:|r %s is off. What it saved is kept.",
    FEATURE_UNKNOWN = "|cffff8040Dossier:|r There is no feature called \"%s\". Try bio, kills, session, shop, shots, or companions.",
    SECTION_OFF_SUFFIX = " (off)",
    TAB_SHOPPING = "Shopping",
    SHOPPING_PLACEHOLDER = "Shift-click or drag an item or recipe, or type a name",
    SHOPPING_ADD = "Add",
    SHOPPING_REMIND = "Remind me at vendors and on login",
    SHOPPING_SUGGEST = "Suggest from bags",
    SHOPPING_SUGGESTED = "Added %d food and drink item%s from your bags.",
    SHOPPING_SUGGEST_NONE = "No new food or drink in your bags.",
    SHOPPING_CLEAR = "Clear finished",
    SHOPPING_EMPTY = "Your shopping list is empty. Shift-click an item or a recipe into the box above, drag an item onto it, or type a name.",
    SHOPPING_SUMMARY = "%d of %d items ready",
    SHOPPING_IMPORTED = "Copied from %s",
    SHOPPING_PENDING = "Open your %s window once to read its reagents.",
    SHOPPING_PENDING_UNKNOWN = "Open its profession window once to read its reagents.",
    SHOPPING_READY = "ready",
    SHOPPING_PENDING_SHORT = "no reagents yet",
    SHOPPING_NEED = "need %s",
    SHOPPING_NOT_FOUND = "Dossier could not find \"%s\". Shift-click it from your bags or a profession window instead.",
    SHOPPING_DUPLICATE = "That item is already on the list. Use + to raise its amount.",
    SHOPPING_SET_BY_YOU = "%s set by you",
    SHOPPING_FOR_RECIPE = "%s for %s x%s",
    SHOPPING_TOOLTIP_HAVE = "Bags %s, bank %s",
    SHOPPING_TOOLTIP_HINT = "+ and - change your own amount. Shift-click for 5.",
    SHOPPING_LOGIN = "|cff5cc8a8Dossier:|r Shopping list: %s.",
    SHOPPING_VENDOR = "|cff5cc8a8Dossier:|r This vendor sells %d thing%s on your shopping list: %s.",
    SHOPPING_EXPORT_EMPTY = "Nothing on the shopping list.",
}

C.CHARACTERS_PER_TOKEN = 4
C.TOKENS_SMALL = 8000
C.TOKENS_MEDIUM = 32000

C.EQUIPMENT_SLOTS = {
    { slotId = INVSLOT_HEAD, slotToken = "HeadSlot", label = "Head" },
    { slotId = INVSLOT_NECK, slotToken = "NeckSlot", label = "Neck" },
    { slotId = INVSLOT_SHOULDER, slotToken = "ShoulderSlot", label = "Shoulder" },
    { slotId = INVSLOT_BACK, slotToken = "BackSlot", label = "Back" },
    { slotId = INVSLOT_CHEST, slotToken = "ChestSlot", label = "Chest" },
    { slotId = INVSLOT_BODY or INVSLOT_SHIRT, slotToken = "ShirtSlot", label = "Shirt" },
    { slotId = INVSLOT_TABARD, slotToken = "TabardSlot", label = "Tabard" },
    { slotId = INVSLOT_WRIST, slotToken = "WristSlot", label = "Wrist" },
    { slotId = INVSLOT_HAND, slotToken = "HandsSlot", label = "Hands" },
    { slotId = INVSLOT_WAIST, slotToken = "WaistSlot", label = "Waist" },
    { slotId = INVSLOT_LEGS, slotToken = "LegsSlot", label = "Legs" },
    { slotId = INVSLOT_FEET, slotToken = "FeetSlot", label = "Feet" },
    { slotId = INVSLOT_FINGER1, slotToken = "Finger0Slot", label = "Finger 1" },
    { slotId = INVSLOT_FINGER2, slotToken = "Finger1Slot", label = "Finger 2" },
    { slotId = INVSLOT_TRINKET1, slotToken = "Trinket0Slot", label = "Trinket 1" },
    { slotId = INVSLOT_TRINKET2, slotToken = "Trinket1Slot", label = "Trinket 2" },
    { slotId = INVSLOT_MAINHAND, slotToken = "MainHandSlot", label = "Main Hand" },
    { slotId = INVSLOT_OFFHAND, slotToken = "SecondaryHandSlot", label = "Off Hand" },
}

C.SKILL_CATEGORY_LABELS = {
    PROFESSIONS = "Professions",
    SECONDARY = "Secondary Skills",
    WEAPON = "Weapon Skills",
    OTHER = "Other Skills",
}